version: '3'

services:
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - '8081:8080'
    environment:
      SWAGGER_JSON: /schema/schema.yml
    volumes:
      - ./schema/schema.yml:/schema/schema.yml
